### ISSUE TITLE
Pots

### ISSUE THREAD

**Issue by katjap** [ElectroTechnique/TSynth-Teensy4.1#17]
It looks like all the pots are used as voltage dividers so 100k pots should work just as well right?
I ask in Issues because I have 100+ 100k RV09s on hand and zero in 33k, and I suspect that others who usually work in the Kosmo synth format likely also have a bunch of 100k RV09s, so it would be nice for everyone to be able to see an answer.

Thanks!

**Comment by ElectroTechnique** [comment]
100k pots will work but there will be greater susceptibility to noise due to the lower current. I would not recommend them. TSynth uses 10k pots and these have 0.1uf caps and code to deal with noise that causes parameter changes. I would buy 10Ks, don't risk problems with 33 pots that you can't easily desolder.
